# Generated by Django 3.1.7 on 2021-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('uniqueID', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('document', models.FileField(null=True, upload_to='Files/')),
            ],
        ),
    ]
