# Generated by Django 3.1.7 on 2022-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_auto_20210621_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='Files/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
