# Generated by Django 3.1.7 on 2021-04-08 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_auto_20210408_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
