# Generated by Django 3.1.7 on 2021-04-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_auto_20210408_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(),
        ),
    ]
